#!/bin/bash

# Autostart
dex -a -s ~/.config/autostart -w
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
eww open bar &
dunst &
xfce4-power-manager &
udiskie --no-notify &
picom &

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX

# Layout
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.52
bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true