#!/bin/bash

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
~/.config/polybar/launch.sh &
dunst &
xfce4-power-manager &

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Layout
bspc config border_width = 2
bspc config window_gap = 16
bspc config split_ratio = 0.52
bspc config single_monocle true